networks:
  springbus:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - springbus

  # Spring Cloud Config Server
  config-server:
    image: nanachi1027/spring-cloud-config-server:1.0-SNAPSHOT
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - rabbitmq
    networks:
      - springbus

  # Config Client Instances
  config-client-1:
    image: nanachi1027/spring-cloud-bus-app:1.0-SNAPSHOT
    container_name: spring-cloud-bus-app-1
    ports:
      - "8081:8080"
    environment:
      - SPRING_APPLICATION_NAME=spring-cloud-bus-app
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - config-server
      - rabbitmq
    networks:
      - springbus

  config-client-2:
    image: nanachi1027/spring-cloud-bus-app:1.0-SNAPSHOT
    container_name: spring-cloud-bus-app-2
    ports:
      - "8082:8080"
    environment:
      - SPRING_APPLICATION_NAME=spring-cloud-bus-app
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - config-server
      - rabbitmq
    networks:
      - springbus

  config-client-3:
    image: nanachi1027/spring-cloud-bus-app:1.0-SNAPSHOT
    container_name: spring-cloud-bus-app-3
    ports:
      - "8083:8080"
    environment:
      - SPRING_APPLICATION_NAME=spring-cloud-bus-app
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - config-server
      - rabbitmq
    networks:
      - springbus

  config-client-4:
    image: nanachi1027/spring-cloud-bus-app:1.0-SNAPSHOT
    container_name: spring-cloud-bus-app-4
    ports:
      - "8084:8080"
    environment:
      - SPRING_APPLICATION_NAME=spring-cloud-bus-app
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - config-server
      - rabbitmq
    networks:
      - springbus