server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rurutia1027/hands-on-shared-config-repo.git
          searchPaths: Hands-on-Lab.Config-Center/spring-cloud-config
          clone-on-start: true