spring:
  application:
    name: spring-cloud-config-app
  profiles:
    active: prod
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, env
  endpoint:
    refresh:
      enabled: true

# Optional: logging to see when environment changes are detected
logging:
  level:
    org.springframework.cloud: INFO
    com.aston.cloudthread: DEBUG