spring:
  application:
    name: spring-cloud-bus-app
  profiles:
    active: prod
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  # RabbitMQ spring starter configuration
  rabbitmq:
    host: rabbitmq   # Docker service name, not localhost
    port: 5672
    username: guest
    password: guest

# Actuator endpoints exposed
management:
  endpoints:
    web:
      exposure:
        include: health, info, env, refresh, busrefresh, busenv
server:
  port: 8080